Repository directus/docs, pull requests merged in 2022-11, with the labels that each got.

#203 update
  package.json
  pnpm-lock.yaml
Labels: Infrastructure

#214 Fix Server Health Draft Spec Link
  reference/system/server.md
Labels: Edits & Errors & Restructures

#197 The Cookbooks
  .vitepress/config.js
  .vitepress/theme/Layout.vue
  .vitepress/theme/index.js
  configuration/users-roles-permissions.md
  configuration/users-roles-permissions/workflows.md
  cookbook/add-a-recipe.md
  cookbook/data-models/build-a-content-hierarchy.md
  cookbook/data-models/personal-portfolio-using-m2a.md
  cookbook/flows/flows-for-loop.md
  cookbook/flows/generate-work-reports.md
  cookbook/flows/slugify-text-with-run-script.md
  cookbook/permissions/basic-workflows.md
  cookbook/permissions/configure-user-registration.md
  cookbook/permissions/multi-sig-data-access.md
  cookbook/template_shell.md
  dictionary.txt
Labels: New Page
